<?php

namespace App\Dtos\Kardex;
use App\Http\Requests\Protocolar\StoreKardexRequest;
use App\Http\Requests\Protocolar\UpdateKardexRequest;

class StoreKardexDto
{
    public function __construct(
        public readonly ?string $d_fecha_abogado,
        public readonly ?string $d_fecha_confrontado,
        public readonly ?string $d_fecha_digitado,
        public readonly ?string $d_fecha_impreso,
        public readonly ?string $d_fecha_solicitud,
        public readonly ?string $d_fechbajakardex,
        public readonly ?string $d_fechcalificada,
        public readonly ?string $d_fechescritura,
        public readonly ?string $d_feching,
        public readonly ?string $d_fechminuta,
        public readonly ?string $d_fechparte,
        public readonly ?string $d_fechtestimonio,
        public readonly ?int    $i_estado,
        public readonly ?string $i_estadonota,
        public readonly ?int    $i_folfin,
        public readonly ?int    $i_folfinV,
        public readonly ?int    $i_folini,
        public readonly ?int    $i_foliniV,
        public readonly ?int    $i_minuta_usuario,
        public readonly ?string $i_numeroOperacion,
        public readonly ?int    $i_numescritura,
        public readonly ?int    $i_numfol,
        public readonly ?string $i_numminuta,
        public readonly ?int    $i_serfin,
        public readonly ?int    $i_seriefinV,
        public readonly ?int    $i_serieiniV,
        public readonly ?int    $i_serini,
        public readonly ?int    $i_sisgen,
        public readonly ?string $s_abogado,
        public readonly ?string $s_actnot,
        public readonly ?string $s_anno,
        public readonly ?string $s_atendido,
        public readonly ?string $s_compareciente,
        public readonly ?string $s_confrontador,
        public readonly ?string $s_confrontador_seg,
        public readonly ?string $s_digitado,
        public readonly ?string $s_facturar,
        public readonly ?string $s_horaing,
        public readonly ?string $s_impreso,
        public readonly ?string $s_kardex,
        public readonly ?string $s_kardexconex,
        public readonly ?string $s_num_solicitud,
        public readonly ?string $s_numreg,
        public readonly ?string $s_numtom,
        public readonly ?string $s_obstitulo,
        public readonly ?string $s_opcion_escritura,
        public readonly ?string $s_personal_abogado,
        public readonly ?string $s_personal_baja,
        public readonly ?string $s_personal_parte,
        public readonly ?string $s_personal_testimonio,
        public readonly ?string $s_referente,
        public readonly ?string $s_responsable,
        public readonly ?string $s_tipo_tramite,
        public readonly ?string $s_tipokardex,
    )
    {
    }

    public function toArray()
    {
        return [
            'd_fecha_abogado' => $this->d_fecha_abogado,
            'd_fecha_confrontado' => $this->d_fecha_confrontado,
            'd_fecha_digitado' => $this->d_fecha_digitado,
            'd_fecha_impreso' => $this->d_fecha_impreso,
            'd_fecha_solicitud' => $this->d_fecha_solicitud,
            'd_fechbajakardex' => $this->d_fechbajakardex,
            'd_fechcalificada' => $this->d_fechcalificada,
            'd_fechescritura' => $this->d_fechescritura,
            'd_feching' => $this->d_feching,
            'd_fechminuta' => $this->d_fechminuta,
            'd_fechparte' => $this->d_fechparte,
            'd_fechtestimonio' => $this->d_fechtestimonio,
            'i_estado' => $this->i_estado,
            'i_estadonota' => $this->i_estadonota,
            'i_folfin' => $this->i_folfin,
            'i_folfinV' => $this->i_folfinV,
            'i_folini' => $this->i_folini,
            'i_foliniV' => $this->i_foliniV,
            'i_minuta_usuario' => $this->i_minuta_usuario,
            'i_numeroOperacion' => $this->i_numeroOperacion,
            'i_numescritura' => $this->i_numescritura,
            'i_numfol' => $this->i_numfol,
            'i_numminuta' => $this->i_numminuta,
            'i_serfin' => $this->i_serfin,
            'i_seriefinV' => $this->i_seriefinV,
            'i_serieiniV' => $this->i_serieiniV,
            'i_serini' => $this->i_serini,
            'i_sisgen' => $this->i_sisgen,
            's_abogado' => $this->s_abogado,
            's_actnot' => $this->s_actnot,
            's_anno' => $this->s_anno,
            's_atendido' => $this->s_atendido,
            's_compareciente' => $this->s_compareciente,
            's_confrontador' => $this->s_confrontador,
            's_confrontador_seg' => $this->s_confrontador_seg,
            's_digitado' => $this->s_digitado,
            's_facturar' => $this->s_facturar,
            's_horaing' => $this->s_horaing,
            's_impreso' => $this->s_impreso,
            's_kardex' => $this->s_kardex,
            's_kardexconex' => $this->s_kardexconex,
            's_num_solicitud' => $this->s_num_solicitud,
            's_numreg' => $this->s_numreg,
            's_numtom' => $this->s_numtom,
            's_obstitulo' => $this->s_obstitulo,
            's_opcion_escritura' => $this->s_opcion_escritura,
            's_personal_abogado' => $this->s_personal_abogado,
            's_personal_baja' => $this->s_personal_baja,
            's_personal_parte' => $this->s_personal_parte,
            's_personal_testimonio' => $this->s_personal_testimonio,
            's_referente' => $this->s_referente,
            's_responsable' => $this->s_responsable,
            's_tipo_tramite' => $this->s_tipo_tramite,
            's_tipokardex' => $this->s_tipokardex,
        ];
    }

    public static function fromApiRequest(StoreKardexRequest|UpdateKardexRequest $request): StoreKardexDto
    {
        return new self(
            d_fecha_abogado: $request->validated('d_fecha_abogado'),
            d_fecha_confrontado: $request->validated('d_fecha_confrontado'),
            d_fecha_digitado: $request->validated('d_fecha_digitado'),
            d_fecha_impreso: $request->validated('d_fecha_impreso'),
            d_fecha_solicitud: $request->validated('d_fecha_solicitud'),
            d_fechbajakardex: $request->validated('d_fechbajakardex'),
            d_fechcalificada: $request->validated('d_fechcalificada'),
            d_fechescritura: $request->validated('d_fechescritura'),
            d_feching: $request->validated('d_feching'),
            d_fechminuta: $request->validated('d_fechminuta'),
            d_fechparte: $request->validated('d_fechparte'),
            d_fechtestimonio: $request->validated('d_fechtestimonio'),
            i_estado: $request->validated('i_estado'),
            i_estadonota: $request->validated('i_estadonota'),
            i_folfin: $request->validated('i_folfin'),
            i_folfinV: $request->validated('i_folfinV'),
            i_folini: $request->validated('i_folini'),
            i_foliniV: $request->validated('i_foliniV'),
            i_minuta_usuario: $request->validated('i_minuta_usuario'),
            i_numeroOperacion: $request->validated('i_numeroOperacion'),
            i_numescritura: $request->validated('i_numescritura'),
            i_numfol: $request->validated('i_numfol'),
            i_numminuta: $request->validated('i_numminuta'),
            i_serfin: $request->validated('i_serfin'),
            i_seriefinV: $request->validated('i_seriefinV'),
            i_serieiniV: $request->validated('i_serieiniV'),
            i_serini: $request->validated('i_serini'),
            i_sisgen: $request->validated('i_sisgen'),
            s_abogado: $request->validated('s_abogado'),
            s_actnot: $request->validated('s_actnot'),
            s_anno: $request->validated('s_anno'),
            s_atendido: $request->validated('s_atendido'),
            s_compareciente: $request->validated('s_compareciente'),
            s_confrontador: $request->validated('s_confrontador'),
            s_confrontador_seg: $request->validated('s_confrontador_seg'),
            s_digitado: $request->validated('s_digitado'),
            s_facturar: $request->validated('s_facturar'),
            s_horaing: $request->validated('s_horaing'),
            s_impreso: $request->validated('s_impreso'),
            s_kardex: $request->validated('s_kardex'),
            s_kardexconex: $request->validated('s_kardexconex'),
            s_num_solicitud: $request->validated('s_num_solicitud'),
            s_numreg: $request->validated('s_numreg'),
            s_numtom: $request->validated('s_numtom'),
            s_obstitulo: $request->validated('s_obstitulo'),
            s_opcion_escritura: $request->validated('s_opcion_escritura'),
            s_personal_abogado: $request->validated('s_personal_abogado'),
            s_personal_baja: $request->validated('s_personal_baja'),
            s_personal_parte: $request->validated('s_personal_parte'),
            s_personal_testimonio: $request->validated('s_personal_testimonio'),
            s_referente: $request->validated('s_referente'),
            s_responsable: $request->validated('s_responsable'),
            s_tipo_tramite: $request->validated('s_tipo_tramite'),
            s_tipokardex: $request->validated('s_tipokardex'),
        );
    }

}
